defaults:
  - base
  - _self_

# YOLOX Base Configuration
# Centralizing official YOLOX hyperparameters for all variants
learning_rate: 1e-3
weight_decay: 5e-4
warmup_epochs: 5
download_pretrained: true
pretrain_weights: null
freeze_backbone_epochs: 0

# Normalization parameters for YOLOX (keeps raw 0-255 values)
image_mean: [0.0, 0.0, 0.0]
image_std: [1.0, 1.0, 1.0]
