# Object Detection Training Configuration
# =========================================
#
# Usage:
#   python -m object_detection_training.task_manager
#   python -m object_detection_training.task_manager model=rfdetr_nano
#   python -m object_detection_training.task_manager model=yolox_s

defaults:
  - _self_
  - task: train
  - model: rfdetr_small
  - data: coco
  - trainer: default
  - callbacks: default
  - logging: null

# Global Parameters
input_height: 576
input_width: 576

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
