# RFDETR Nano Model Configuration
_target_: object_detection_training.models.rfdetr_lightning.RFDETRNanoModel
# num_classes: auto-detected from dataset if not specified
num_classes: null
resolution: 640  # Must be divisible by 64
learning_rate: 1e-4
lr_encoder: 1.5e-4
weight_decay: 1e-4
warmup_epochs: 5
use_ema: true
ema_decay: 0.9999
download_pretrained: true
pretrain_weights: null
