defaults:
  - rfdetr_base
  - _self_

# RFDETR Large Model Configuration
# Resolution 560 matches RFDETRLargeConfig from rfdetr package
_target_: object_detection_training.models.rfdetr_lightning.RFDETRLargeModel
