defaults:
  - rfdetr_base
  - _self_

# RFDETR Medium Model Configuration
# Resolution 576 matches RFDETRMediumConfig from rfdetr package
_target_: object_detection_training.models.rfdetr_lightning.RFDETRMediumModel
