defaults:
  - rfdetr_base
  - _self_

# RFDETR Small Model Configuration
# Resolution 512 matches RFDETRSmallConfig from rfdetr package
_target_: object_detection_training.models.rfdetr_lightning.RFDETRSmallModel
