defaults:
  - base
  - _self_

# RFDETR Large Model Configuration
_target_: object_detection_training.models.rfdetr_lightning.RFDETRLargeModel
learning_rate: 1e-4
lr_encoder: 1.5e-4
weight_decay: 1e-4
download_pretrained: true
pretrain_weights: null
