defaults:
  - base
  - _self_

# RFDETR Small Model Configuration
_target_: object_detection_training.models.rfdetr_lightning.RFDETRSmallModel
input_size: 560
learning_rate: 1e-4
weight_decay: 1e-4
download_pretrained: true
pretrain_weights: null
