defaults:
  - base
  - _self_

# RFDETR Nano Model Configuration
_target_: object_detection_training.models.rfdetr_lightning.RFDETRNanoModel
input_size: 384  # Must be divisible by 64
learning_rate: 1e-4
lr_encoder: 1.5e-4
weight_decay: 1e-4
warmup_epochs: 5
download_pretrained: true
pretrain_weights: null
