# YOLOX Medium Model Configuration
_target_: object_detection_training.models.yolox_lightning.YOLOXMModel
num_classes: 80
learning_rate: 1e-3
weight_decay: 5e-4
warmup_epochs: 5
use_ema: true
ema_decay: 0.9998
download_pretrained: true
pretrain_weights: null
input_size: 640
