defaults:
  - base
  - _self_

# YOLOX Nano Model Configuration
_target_: object_detection_training.models.yolox_lightning.YOLOXNanoModel
learning_rate: 1e-3
weight_decay: 5e-4
download_pretrained: true
pretrain_weights: null
input_size: 416
